---
namespace: "eigenstate"
name: "ipa"
version: "1.10.2"
description: >-
  An Ansible collection for Red Hat IdM / FreeIPA with dynamic
  inventory plus IdM vault retrieval and lifecycle automation,
  Kerberos principal state, Kerberos keytab retrieval,
  certificate issuance, OTP workflows, delegated user-lease control, DNS
  record inspection, sudo policy inspection, SELinux user map inspection, and
  HBAC rule inspection and access testing for Kerberos-friendly automation,
  AAP, and secure secret delivery.

authors:
  - "Greg Procunier"

repository: "https://github.com/gprocunier/eigenstate-ipa"
documentation: "https://gprocunier.github.io/eigenstate-ipa/"
homepage: "https://gprocunier.github.io/eigenstate-ipa/"
issues: "https://github.com/gprocunier/eigenstate-ipa/issues"

readme: "README.md"

license:
  - "GPL-3.0-or-later"

tags:
  - "linux"
  - "identity"
  - "ipa"
  - "freeipa"
  - "idm"
  - "inventory"
  - "vault"
  - "automation"
  - "principal"
  - "cert"
  - "secrets"
  - "keytab"
  - "otp"
  - "kerberos"
  - "rhel"
  - "selinux"
  - "hbac"
  - "policy"

build_ignore:
  - "*.tar.gz"
  - ".git"
  - ".ansible"
