---
namespace: "eigenstate"
name: "ipa"
version: "1.0.3"
description: >-
  An Ansible collection for Red Hat IdM / FreeIPA with dynamic
  inventory and vault lookup plugins for Kerberos-friendly automation,
  AAP, and secure secret retrieval.

authors:
  - "Greg Procunier"

repository: "https://github.com/gprocunier/eigenstate-ipa"
documentation: "https://gprocunier.github.io/eigenstate-ipa/"
homepage: "https://gprocunier.github.io/eigenstate-ipa/"
issues: "https://github.com/gprocunier/eigenstate-ipa/issues"

readme: "README.md"

license:
  - "GPL-3.0-or-later"

tags:
  - "linux"
  - "identity"
  - "ipa"
  - "freeipa"
  - "idm"
  - "inventory"
  - "vault"
  - "secrets"
  - "rhel"

build_ignore:
  - "*.tar.gz"
  - ".git"
