---
eigenstate_k8s_secret_name: idm-vault-secret
eigenstate_k8s_secret_namespace: default
eigenstate_k8s_secret_type: Opaque
eigenstate_k8s_secret_data:
  artifact: static-validation-value

eigenstate_k8s_secret_render_only: true
eigenstate_k8s_secret_apply: false
eigenstate_k8s_secret_render_review_manifest: true
eigenstate_k8s_secret_write_payload_manifest: false
eigenstate_k8s_secret_no_log: true

eigenstate_k8s_secret_output_dir: ./artifacts
eigenstate_k8s_secret_basename: kubernetes-secret-from-idm-vault
eigenstate_k8s_secret_labels:
  app.kubernetes.io/managed-by: eigenstate.ipa
  app.kubernetes.io/component: workload-secret-delivery
eigenstate_k8s_secret_annotations: {}
eigenstate_k8s_secret_correlation_id: ""

eigenstate_k8s_secret_live_lookup_enabled: false
eigenstate_k8s_secret_vault_name: ""
eigenstate_k8s_secret_vault_scope: shared
eigenstate_k8s_secret_vault_key: artifact
eigenstate_k8s_secret_server: ""
eigenstate_k8s_secret_kerberos_keytab: ""
eigenstate_k8s_secret_ipaadmin_principal: admin
eigenstate_k8s_secret_ipaadmin_password: ""
eigenstate_k8s_secret_verify: ""
eigenstate_k8s_secret_username: ""
eigenstate_k8s_secret_service: ""
eigenstate_k8s_secret_delegate_to: localhost

eigenstate_k8s_secret_kubeconfig: ""
eigenstate_k8s_secret_context: ""
eigenstate_k8s_secret_kubectl: kubectl
